title: Kadaster Labs
description: Kadaster research lab
# theme: theme
repository: kadaster/labs.kadaster.nl
port: 5000
host: 127.0.1.1
exclude: [docker-compose.yml]
defaults:
  - scope:
      path: ""
      type: pages
    values:
      banner: /navigatie/banner.jpg
  - scope:
      # this is maybe too general: in future maybe we have access to img / pdf input in LLM api
      # also excluding some LD data
      path: "assets"
    values:
      sitemap: false

# https://github.com/jekyll/jekyll-sitemap#:~:text=Note%20on%20Use,of%20plugins.
url: "https://labs.kadaster.nl"
plugins:
  - jekyll-sitemap
